const express = require('express')
const router = express.Router()
const { getRepo, getRepos, createRepo, updateRepo, deleteRepo, getRepoFolders, createRepoFolder, getNotes, createNote, updateNote, getNote, getRepoFolder, deleteRepoFolder, noteRepoFolder, startRepoSession, endRepoSession, getFlashcards } = require('../controllers/repoController')
const protect = require('../middleware/auth')

router.get('/', protect, getRepos)
router.get('/:id', protect, getRepo)
router.get('/:id/:parent/folders', protect, getRepoFolders)
router.get('/:id/folder', protect, getRepoFolder)
router.get('/:id/:parent/notes', protect, getNotes)
router.get('/:id/:parent/flashcards', protect, getFlashcards)
router.get('/:id/notes', protect, getNote)
router.post('/', protect, createRepo)
router.post('/folders', protect, createRepoFolder)
router.post('/notes', protect, createNote)
router.post('/:userId/sessionStart', protect, startRepoSession)
router.post('/:id/sessionEnd', protect, endRepoSession)
router.put('/:id', protect, updateRepo)
router.put('/:id/notes', protect, updateNote)
router.delete('/:id', protect, deleteRepo)
router.delete('/:id/:folderId/folders', protect, deleteRepoFolder)
router.delete('/:id/:noteId/notes', protect, noteRepoFolder)

module.exports = router